export type RootStackParamList = {
  "Trang Đăng Nhập": undefined;
  "Trang Đăng Ký": undefined;
  "Trang Chủ": undefined;
  "Giỏ Hàng": undefined;
  "Tài Khoản": undefined;
  "Quản Lý Đơn Hàng": undefined;
  "Thêm Sản Phẩm Vào Giỏ": undefined;
  "Chi Tiết Đơn Hàng": undefined;
  "Tạo Đơn Hàng": undefined;
  "Trang Chủ Admin": undefined;
  "Cập Nhật Tài Khoản": undefined;
  "Chi Tiết Sản Phẩm": undefined;
  "Quản Lý Admin": undefined;
  "Quản Lý User": undefined;
  "Thêm Admin": undefined;
  "Cập Nhật Admin": undefined;
  "Quản Lý Sản Phẩm": undefined;
  "Quản Lý Danh Mục": undefined;
  "Quản Lý Đơn Hàng Admin": undefined;
  "Chi Tiết Đơn Hàng Admin": undefined;
  "Báo Cáo Doanh Thu": undefined;
  "Sản Phẩm Bán Chạy": undefined;
  "Thêm Sản Phẩm": undefined;
  "Cập Nhật Sản Phẩm": undefined;
  "Cập Nhật Danh Mục": undefined;
  "Thêm Danh Mục": undefined;
  "Phản Hồi": undefined;
  "Khuyến Mãi": undefined;
  "Thêm Khuyến Mãi": undefined;
  "Chọn Khuyến Mãi": undefined;
  "Quản Lý Khuyến Mãi": undefined;
  "Quản Lý Banner": undefined;
  "Cập Nhật Banner": { bannerId: string };
  "Thêm Banner": undefined;
  "Yêu Thích": undefined;
  "Chat Admin":undefined;
};
